// Alerts

export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const CLEAR_ALERTS = "CLEAR_ALERTS"

// AUTH

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const CLEAR_USER = 'CLEAR_USER'

// GET ALL RECIPES
export const GET_RECIPES = 'GET_RECIPES'
export const GET_RECIPES_ERROR = 'GET_RECIPES_ERROR'
export const UPDATE_RECIPES_LS = 'UPDATE_RECIPES_LS'
export const UPDATE_RECIPES_LS_ERROR = 'UPDATE_RECIPES_LS_ERROR'
export const CLEAR_RECIPE = 'CLEAR_RECIPE'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// GET INDIVIDUAL RECIPES
export const GET_RECIPE = 'GET_RECIPE'
export const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR'
export const UPDATE_RECIPE_LS = 'UPDATE_RECIPE_LS'
export const UPDATE_RECIPE_LS_ERROR = 'UPDATE_RECIPE_LS_ERROR'
export const CREATE_RECIPE = 'CREATE_RECIPE'
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR'
export const EDIT_RECIPE = 'EDIT_RECIPE'
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR'


// SEARCH
export const SEARCH = 'SEARCH'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const GET_SEARCH_RECIPES = 'GET_SEARCH_RECIPES'

// GET ALL COOKBOOK
export const GET_COOKBOOKS = 'GET_COOKBOOKS'
export const GET_COOKBOOKS_ERROR = 'GET_COOKBOOKS_ERROR'
export const UPDATE_COOKBOOKS_LS = 'UPDATE_COOKBOOKS_LS'
export const UPDATE_COOKBOOKS_LS_ERROR = 'UPDATE_COOKBOOKS_LS_ERROR'
export const ADD_RECIPE_TO_COOKBOOKS = 'ADD_RECIPE_TO_COOKBOOKS'
export const ADD_RECIPE_TO_COOKBOOKS_ERROR = 'ADD_RECIPE_TO_COOKBOOKS_ERROR'
export const CREATE_COOKBOOK = 'CREATE_COOKBOOK'
export const CREATE_COOKBOOK_ERROR = 'CREATE_COOKBOOK_ERROR'
export const DELETE_COOKBOOK = 'DELETE_COOKBOOK'
export const DELETE_COOKBOOK_ERROR = 'DELETE_COOKBOOK_ERROR'
export const RENAME_COOKBOOK = 'RENAME_COOKBOOK'
export const RENAME_COOKBOOK_ERROR = 'RENAME_COOKBOOK_ERROR'


// Individual cookbook
export const GET_COOKBOOK = 'GET_COOKBOOK'
export const GET_COOKBOOK_ERROR = 'GET_COOKBOOK_ERROR'
export const LOAD_COOKBOOK_RECIPES = 'LOAD_COOKBOOK_RECIPES'
export const LOAD_COOKBOOK_RECIPES_ERROR = 'LOAD_COOKBOOK_RECIPES_ERROR'
export const REMOVE_RECIPE = 'REMOVE_RECIPE'
export const REMOVE_RECIPE_ERROR = 'REMOVE_RECIPE_ERROR'











