export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const CLEAR_ALERTS = "CLEAR_ALERTS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const GET_RECIPE = 'GET_RECIPE'
export const RECIPE_ERROR = 'RECIPE_ERROR'
export const CLEAR_USER = 'CLEAR_USER'
export const CREATE_RECIPE = 'CREATE_RECIPE'
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR'
export const EDIT_RECIPE = 'EDIT_RECIPE'
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR'
export const GET_RECIPES = 'GET_RECIPES'
export const RECIPES_ERROR = 'GET_RECIPES'
export const CLEAR_RECIPE = 'CLEAR_RECIPE'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SEARCH = 'SEARCH'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const GET_SEARCH_RECIPES = 'GET_SEARCH_RECIPES'

export const GET_COOKBOOKS = 'GET_COOKBOOKS'
export const GET_COOKBOOK = 'GET_COOKBOOK'
export const GET_COOKBOOKS_ERROR = 'GET_COOKBOOKS_ERROR'
export const LOAD_COOKBOOK_RECIPES = 'LOAD_COOKBOOK_RECIPES'
export const CREATE_COOKBOOK = 'CREATE_COOKBOOK'
export const UPDATE_COOKBOOKS = 'UPDATE_COOKBOOKS'
export const DELETE_COOKBOOK = 'DELETE_COOKBOOK'
export const UPDATE_COOKBOOK = 'UPDATE_COOKBOOK'




